# Hello World

In [2]:
print("Hello World")
print("Nameste Duniya")

Hello World
Nameste Duniya


# Sum of Two Numbers

In [3]:
x=9
y=8
print(x+y)

17


In [4]:
mylist= [1,2,3,4,5]
print(mylist)
mylist.append(6)
print(mylist)
mylist.remove(3)
print(mylist)
mylist.insert(2,3)
print(mylist)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 4, 5, 6]
[1, 2, 3, 4, 5, 6]


In [5]:
mytuple= (1,2,3,4,5)
print(mytuple)
print(mytuple[2])
mytuple= mytuple + (6,)
print(mytuple)
print(mytuple.count(3))
print(mytuple.index(3))

(1, 2, 3, 4, 5)
3
(1, 2, 3, 4, 5, 6)
1
2


In [6]:
mydict= {'a':1, 'b':2, 'c':3}
print(mydict)
mydict.update({'d': 4})
print(mydict)

{'a': 1, 'b': 2, 'c': 3}
{'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [7]:
import numpy as np

In [8]:
list1= np.array([[1, 2, 3], [4, 5, 6]]) 
tuple1= np.array(("1", "2", "3"))
print(list1)
print(tuple1)
print(list1.ndim)
print(tuple1.ndim)

[[1 2 3]
 [4 5 6]]
['1' '2' '3']
2
1


In [9]:
print(list1.shape)
print(tuple1.shape)
newarr= np.array(list1, ndmin=2, dtype= int)
print(newarr)

(2, 3)
(3,)
[[1 2 3]
 [4 5 6]]


In [10]:
print(list1.dtype)

int32


In [11]:
list4= np.array([1, 2, 3, 4, 5, 6, 7, 8, 2, 5, 9, 10])
newarray= list4.reshape(4,3)
print(newarray)
newarray= list4.reshape(-1)
print(newarray)
newarray= list4.reshape(-1, 2,2)
print(newarray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  2]
 [ 5  9 10]]
[ 1  2  3  4  5  6  7  8  2  5  9 10]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 2  5]
  [ 9 10]]]


In [12]:
sortarr= np.array(['Lakshy', 'Aman', 'Nandini', 'Diya'])
x= [True, False, True, False]
newarr= sortarr[x]
print(newarr)

['Lakshy' 'Nandini']


In [13]:
print(sortarr[::-1])

['Diya' 'Nandini' 'Aman' 'Lakshy']


# Operations of arthemetic

In [14]:
print(list4[2]+list4[4])    #addition
print(list4[2]-list4[4])    #subtraction
print(list4[2]*list4[4])    #multiplication
print(list4[2]/list4[4])    #division
print(list4[2]%list4[4])    #modulus
print(list4[2]//list4[4])   #floor division
print(list4[2]**list4[4])   #exponentiation

8
-2
15
0.6
3
0
243


In [ ]:
from numpy import random
arr11= np.array([1, 2, 3, 4, 5, 6])
#print(np.random.shuffle(arr11))
#print(arr11)
# print(np.random.permutation(arr11))

print(np.random.permutation(arr11)   )
print(arr11)
#print(arr11)

[1 2 3 4 5 6]


Note: Shuffle and permutation operations cannot be accessed directly from the numpy even if you had imported random funtion. So for that you have to use dot operator to access those functions. 

In [ ]:
a= np.array([1, 2, 3, 4, 5])

In [ ]:
print(a)

[1 2 3 4 5]


In [ ]:
print(a[2]+a[3])

7
