# HELLO WORLD!!
## hello
### hello

In [39]:
print("Hello World")
print("Nameste Duniya")

Hello World
Nameste Duniya


# Sum of two Numbers

In [40]:
x=9
y=8
print(x+y)

17


# List Operations

In [41]:
mylist= [1,2,3,4,5]
print(mylist)
mylist.append(6)
print(mylist)
mylist.remove(3)
print(mylist)
mylist.insert(2,3)
print(mylist)


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 4, 5, 6]
[1, 2, 3, 4, 5, 6]


# Tuple Operations

In [42]:
mytuple= (1,2,3,4,5)
print(mytuple)
print(mytuple[2])
mytuple= mytuple + (6,)
print(mytuple)
print(mytuple.count(3))
print(mytuple.index(3))

(1, 2, 3, 4, 5)
3
(1, 2, 3, 4, 5, 6)
1
2


# Dictionaries Operations

In [43]:
mydict= {'a':1, 'b':2, 'c':3}
print(mydict)
mydict.update({'d': 4})
print(mydict)

{'a': 1, 'b': 2, 'c': 3}
{'a': 1, 'b': 2, 'c': 3, 'd': 4}


# Numpy

In [62]:
import numpy as np
import pandas as pd
import matplotlib as plty;

In [64]:
list1= np.array([1, 2, 3]) 
tuple1= np.array(("1", "2", "3"))

In [65]:
list123= np.array([[1, 2, 3], [4, 5, 6]])
print(list123.ndim)

2


In [66]:
print(type(list1))
print(list1.dtype)

<class 'numpy.ndarray'>
int32


In [67]:
list2= np.array(["1", "2", "6"], dtype= "i")
print(list2)

[1 2 6]


In [68]:
print(list2[2])

6


In [50]:
list9= list1.copy()
list9[1]= 7
list1[0]= 9
print(list1)
print(list9)

[9 2 3]
[1 7 3]


In [69]:
list3= list2.view()
list3[0]= 3
print(list3)
print(list2)

[3 2 6]
[3 2 6]


# Reshaping an array

In [73]:
list4= np.array((1, 2, 3, 4, 5, 6, 7, 8, 2, 5, 9, 10))
newarray= list4.reshape(4,3)
print(newarray)
newarray= list4.reshape(-1)
print(newarray)
newarray= list4.reshape(-1, 2,2)
print(newarray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  2]
 [ 5  9 10]]
[ 1  2  3  4  5  6  7  8  2  5  9 10]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 2  5]
  [ 9 10]]]


In [74]:
#sortarray= np.array([3, 2, 0, 1, 8, 6, 4, 5, 7])
sortarr= np.array([2, 5, 3, 8, 2, 8, 9])
print(np.sort(sortarr))

[2 2 3 5 8 8 9]


In [76]:
sortarr= np.array(['Ram', 'shyam', 'Tarun'])
print(np.sort(sortarr))

['Ram' 'Tarun' 'shyam']


In [55]:
sortarr= np.array(['Lakshy', 'Aman', 'Nandini', 'Diya'])
x= [True, False, True, False]
newarr= sortarr[x]
print(newarr)

['Lakshy' 'Nandini']


In [56]:
print(sortarr[::-1])

['Diya' 'Nandini' 'Aman' 'Lakshy']


In [57]:
arr9= np.array([1, 2, 3, 4, 5, 6,7, 8])

# Operations of arthemetic

In [58]:
print(arr9[2]+arr9[4])
print(arr9[2]-arr9[4])

8
-2


In [84]:
from numpy import random
arr11= np.array([1, 2, 3, 4, 5, 6])
print(np.random.shuffle(arr11))
print(arr11)
# print(np.random.permutation(arr11))

np.random.permutation(arr11)   
print(arr11)
#print(arr11)

None
[6 2 5 1 4 3]
[6 2 5 1 4 3]


In [60]:
np.savetxt('newfile2.csv', arr11)    
arr12= np.loadtxt('newfile2.csv')
print(arr12)

[1. 5. 6. 2. 4. 3.]


In [61]:
np.save('newfile2.npy', arr11)    
arr12= np.load('newfile2.npy')
print(arr12)

[1 5 6 2 4 3]
