# HELLO WORLD!!
## hello
### hello

In [3]:
print("Hello World")
print("Nameste Duniya")

Hello World
Nameste Duniya


# Sum of two Numbers

In [4]:
x=9
y=8
print(x+y)

17


# List Operations

In [5]:
mylist= [1,2,3,4,5]
print(mylist)
mylist.append(6)
print(mylist)
mylist.remove(3)
print(mylist)
mylist.insert(2,3)
print(mylist)


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 4, 5, 6]
[1, 2, 3, 4, 5, 6]


# Tuple Operations

In [6]:
mytuple= (1,2,3,4,5)
print(mytuple)
print(mytuple[2])
mytuple= mytuple + (6,)
print(mytuple)
print(mytuple.count(3))
print(mytuple.index(3))

(1, 2, 3, 4, 5)
3
(1, 2, 3, 4, 5, 6)
1
2


# Dictionaries Operations

In [7]:
mydict= {'a':1, 'b':2, 'c':3}
print(mydict)
mydict.update({'d': 4})
print(mydict)

{'a': 1, 'b': 2, 'c': 3}
{'a': 1, 'b': 2, 'c': 3, 'd': 4}


# Numpy

In [8]:
import numpy as np
import pandas as pd
import matplotlib as plty;

In [9]:
list1= np.array([1, 2, 3]) 
tuple1= np.array(("1", "2", "3"))

In [10]:
print(list1.ndim)

1


In [11]:
print(type(list1))
print(list1.dtype)

<class 'numpy.ndarray'>
int32


In [12]:
list2= np.array(["1", "2", "5"], dtype= "i")

In [13]:
print(list1[2])

3


In [14]:
list2= list1.copy()
print(list1)
print(list2)

[1 2 3]
[1 2 3]


In [15]:
list3= list2.view()
list3[0]= 7
print(list3)
print(list2)

[7 2 3]
[7 2 3]


In [16]:
list4= np.array((1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
                )
newarray= list4.reshape(4,3)
print(newarray)
newarray= list4.reshape(-1)
print(newarray)
newarray= list4.reshape(2,3,-1)
print(newarray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [17]:
sortarray= np.array([3, 2, 0, 1, 8, 6, 4, 5, 7])
print(np.sort(sortarray))

[0 1 2 3 4 5 6 7 8]


In [18]:
sortarr= np.array(['Lakshy', 'Aman', 'Nandini', 'Diya', 'Rahul', 'Aman'])
print(np.sort(sortarr))

['Aman' 'Aman' 'Diya' 'Lakshy' 'Nandini' 'Rahul']


In [19]:
sortarr= np.array(['Lakshy', 'Aman', 'Nandini', 'Diya'])
x= [True, False, True, False]
newarr= sortarr[x]
print(newarr)

['Lakshy' 'Nandini']


In [20]:
print(sortarr[::-1])

['Diya' 'Nandini' 'Aman' 'Lakshy']


In [21]:
arr9= np.array([1, 2, 3, 4, 5, 6,7, 8])

In [23]:
print(arr9[2]+arr9[4])
print(arr9[2]-arr9[4])

8
-2


In [ ]:
arr11= np.array([1, 2, 3, 4, 5, 6])
np.random.shuffle(arr11)
print(arr11)
print(np.random.permutation(arr11))
#print(arr11)

[4 5 3 2 1 6]
[1 3 5 2 4 6]


In [ ]:
np.savetxt('newfile2.csv', arr11)    
arr12= np.loadtxt('newfile2.csv')
print(arr12)

[4 5 3 2 1 6]


In [ ]:
np.save('newfile2.npy', arr11)    
arr12= np.load('newfile2.npy')
print(arr12)