# HELLO WORLD!!
## hello
### hello

In [39]:
print("Hello World")
print("Nameste Duniya")

Hello World
Nameste Duniya


# Sum of two Numbers

In [40]:
x=9
y=8
print(x+y)

17


# List Operations

In [41]:
mylist= [1,2,3,4,5]
print(mylist)
mylist.append(6)
print(mylist)
mylist.remove(3)
print(mylist)
mylist.insert(2,3)
print(mylist)


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 4, 5, 6]
[1, 2, 3, 4, 5, 6]


# Tuple Operations

In [42]:
mytuple= (1,2,3,4,5)
print(mytuple)
print(mytuple[2])
mytuple= mytuple + (6,)
print(mytuple)
print(mytuple.count(3))
print(mytuple.index(3))

(1, 2, 3, 4, 5)
3
(1, 2, 3, 4, 5, 6)
1
2


# Dictionaries Operations

In [43]:
mydict= {'a':1, 'b':2, 'c':3}
print(mydict)
mydict.update({'d': 4})
print(mydict)

{'a': 1, 'b': 2, 'c': 3}
{'a': 1, 'b': 2, 'c': 3, 'd': 4}


# Numpy

In [62]:
import numpy as np
import pandas as pd
import matplotlib as plty;

In [64]:
list1= np.array([1, 2, 3]) 
tuple1= np.array(("1", "2", "3"))

In [65]:
list123= np.array([[1, 2, 3], [4, 5, 6]])
print(list123.ndim)

2


In [66]:
print(type(list1))
print(list1.dtype)

<class 'numpy.ndarray'>
int32


In [67]:
list2= np.array(["1", "2", "6"], dtype= "i")
print(list2)

[1 2 6]


In [68]:
print(list2[2])

6


In [50]:
list9= list1.copy()
list9[1]= 7
list1[0]= 9
print(list1)
print(list9)

[9 2 3]
[1 7 3]


In [69]:
list3= list2.view()
list3[0]= 3
print(list3)
print(list2)

[3 2 6]
[3 2 6]


# Reshaping an array

In [73]:
list4= np.array((1, 2, 3, 4, 5, 6, 7, 8, 2, 5, 9, 10))
newarray= list4.reshape(4,3)
print(newarray)
newarray= list4.reshape(-1)
print(newarray)
newarray= list4.reshape(-1, 2,2)
print(newarray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  2]
 [ 5  9 10]]
[ 1  2  3  4  5  6  7  8  2  5  9 10]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 2  5]
  [ 9 10]]]


In [74]:
#sortarray= np.array([3, 2, 0, 1, 8, 6, 4, 5, 7])
sortarr= np.array([2, 5, 3, 8, 2, 8, 9])
print(np.sort(sortarr))

[2 2 3 5 8 8 9]


In [76]:
sortarr= np.array(['Ram', 'shyam', 'Tarun'])
print(np.sort(sortarr))

['Ram' 'Tarun' 'shyam']


In [55]:
sortarr= np.array(['Lakshy', 'Aman', 'Nandini', 'Diya'])
x= [True, False, True, False]
newarr= sortarr[x]
print(newarr)

['Lakshy' 'Nandini']


In [56]:
print(sortarr[::-1])

['Diya' 'Nandini' 'Aman' 'Lakshy']


In [57]:
arr9= np.array([1, 2, 3, 4, 5, 6,7, 8])

# Operations of arthemetic

In [58]:
print(arr9[2]+arr9[4])
print(arr9[2]-arr9[4])

8
-2


In [84]:
from numpy import random
arr11= np.array([1, 2, 3, 4, 5, 6])
print(np.random.shuffle(arr11))
print(arr11)
# print(np.random.permutation(arr11))

np.random.permutation(arr11)   
print(arr11)
#print(arr11)

None
[6 2 5 1 4 3]
[6 2 5 1 4 3]


In [60]:
np.savetxt('newfile2.csv', arr11)    
arr12= np.loadtxt('newfile2.csv')
print(arr12)

[1. 5. 6. 2. 4. 3.]


In [61]:
np.save('newfile2.npy', arr11)    
arr12= np.load('newfile2.npy')
print(arr12)

[1 5 6 2 4 3]


In [ ]:
from numpy import linalg
# import numpy as np
a= np.array([[1, 2], [4, 5]])
b= np.array([[7, 8], [10, 11]])

# print(np.dot(a, b))
# print(np.matmul(a, b))
print(np.linalg.det(a))
print(np.linalg.inv(a))
print(np.linalg.matrix_rank(a))

In [ ]:
np.random.seed(1)          # Ensures reproducibility
#print(np.random.rand(3, 3)) # Uniform distribution
print(np.random.randn(3, 3))# Normal distribution
print(np.random.randint(1, 10, (3, 3))) # Random integers
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], 4)) # Random choice

In [ ]:
print(np.random.choice([1, 2, 3, 4, 5], size= (3, 3))) # Random choice
print(np.random.permutation([1, 2, 3, 4, 5])) # Random permutation

In [ ]:
# Save an array to a CSV file
np.savetxt('array_data.csv', arr7, delimiter=',')

# Load the array back from the CSV file
loaded_array = np.loadtxt('array_data.csv', delimiter=',')
print("Loaded Array:")
print(loaded_array)

np.save('array_data.npy', arr7) # Save an array to a binary file
loaded_array = np.load('array_data.npy') # Load the array back from the binary file
print("Loaded Array:")
print(loaded_array)

In [ ]:
import pandas as pd

dict= { 'Name': ['Rahul' , 'Ram', 'shyam'], 
       'Age': ['26', '14', '17'],
       'City': ['Indore', 'Pune', 'Mumbai']
}

a= pd.DataFrame(dict)
print(a)

In [ ]:
data= [10, 20, 30, 40, 50]
series= pd.Series(data, index=[1, 2, 3, 4, 5])
print(series)

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago'], 
    'Gender': ['M', 'M', 'F']
}

df = pd.DataFrame(data, index=['a', 'b', 'c'])
print(df)

In [ ]:
print(df.head()) # Display the first 5 rows of the DataFrame
print(df.tail()) # Display the last 5 rows of the DataFrame 
print(df.info()) # Display information about the DataFrame
print(df.describe()) # Display summary statistics for numerical columns
print(df['Age']>30) # Boolean indexing
print(df[df['Age']>30]) # Filter rows based on a condition
