# HELLO WORLD!!
## Markdown Subheading
### Markdown Paragraph

In [2]:
print("Hello World")
print("Nameste Duniya")

Hello World
Nameste Duniya





# Sum of two Numbers

In [3]:
x=9
y=8
print(x+y)

17


# List Operations

In [4]:
mylist= [1,2,3,4,5]
print(mylist)
mylist.append(6)
print(mylist)
mylist.remove(3)
print(mylist)
mylist.insert(2,3)
print(mylist)


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 4, 5, 6]
[1, 2, 3, 4, 5, 6]


# Tuple Operations

In [5]:
mytuple= (1,2,3,4,5)
print(mytuple)
print(mytuple[2])
mytuple= mytuple + (6,)
print(mytuple)
print(mytuple.count(3))
print(mytuple.index(3))

(1, 2, 3, 4, 5)
3
(1, 2, 3, 4, 5, 6)
1
2


# Dictionaries Operations

In [6]:
mydict= {'a':1, 'b':2, 'c':3}
print(mydict)
mydict.update({'d': 4})
print(mydict)

{'a': 1, 'b': 2, 'c': 3}
{'a': 1, 'b': 2, 'c': 3, 'd': 4}


# Numpy

In [7]:
import numpy as np
import pandas as pd
import matplotlib as plty;

In [8]:
list1= np.array([1, 2, 3]) 
tuple1= np.array(("1", "2", "3"))
print(list1)
print(tuple1)
print(list1.ndim)
print(tuple1.ndim)

[1 2 3]
['1' '2' '3']
1
1


In [9]:
print(type(list1))
print(list1.dtype)

<class 'numpy.ndarray'>
int32


In [10]:
list2= np.array(["1", "2", "5"], dtype= "i")
print(list1[2])

3


In [11]:
list2= list1.copy()
list2[0]= 5
print(list1)
print(list2)

[1 2 3]
[5 2 3]


In [12]:
list3= list2.view()
list3[0]= 7
print(list3)
print(list2)

[7 2 3]
[7 2 3]


In [13]:
list4= np.array((1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12))
newarray= list4.reshape(4,3)
print(newarray)
#newarray= list4.reshape(-1)
#print(newarray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [14]:
newarray[:, [2,0]]= newarray[:, [0,2]]
print(newarray)

[[ 3  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [12 11 10]]


In [15]:
sortarray= np.array([3, 2, 0, 1, 8, 6, 4, 5, 7])
print(np.sort(sortarray))

[0 1 2 3 4 5 6 7 8]


In [16]:
sortarr= np.array(['Lakshy', 'Aman', 'Nandini', 'Diya', 'Rahul', 'Aman'])
print(np.sort(sortarr))

['Aman' 'Aman' 'Diya' 'Lakshy' 'Nandini' 'Rahul']


In [17]:
sortarr= np.array(['Lakshy', 'Aman', 'Nandini', 'Diya'])
x= [True, False, True, False]
newarr= sortarr[x]
print(newarr)
print("Reverse Order:" ,sortarr[::-1])

['Lakshy' 'Nandini']
Reverse Order: ['Diya' 'Nandini' 'Aman' 'Lakshy']


In [18]:
arr4= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
condition= arr4>5
newarr= arr4[condition]
print(newarr)

[ 6  7  8  9 10]


In [19]:
print(arr4[2]+ arr4[5])
print(arr4[2]- arr4[5])
print(arr4[2]* arr4[5])
print(arr4[2]/ arr4[5])
print(arr4[2]% arr4[5])

9
-3
18
0.5
3


In [20]:
arr5= np.array([1, 2, 3, 4, 5])
arr6= np.array([6, 7, 8, 9, 10])
print(np.add(arr5, arr6))  #Addition 
print(np.concatenate((arr5, arr6))) #Concatenation


[ 7  9 11 13 15]
[ 1  2  3  4  5  6  7  8  9 10]


There is a difference between add and concate. Remember add function actually performs addition addition while concate function combines the values of an array.

In [21]:
from numpy import random
random.shuffle(arr5)
print(arr5)
random.permutation(arr5)
print(arr5)
print(arr5)

[5 4 3 1 2]
[5 4 3 1 2]
[5 4 3 1 2]


In [22]:
arr7= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 11, 12, 12, 12, 13, 14, 14, 15, 16])
print(np.split(arr7, 5))
print(arr7.shape)
print(np.flip(arr7))
print(np.unique(arr7))

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 10, 11]), array([12, 12, 12, 13]), array([14, 14, 15, 16])]
(20,)
[16 15 14 14 13 12 12 12 11 10 10  9  8  7  6  5  4  3  2  1]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [23]:
np.savetxt('newfile.csv', arr7)
arr8= np.loadtxt('newfile.csv')
print(arr8)
print(np.load('newfile.npy'))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 10. 11. 12. 12. 12. 13. 14. 14.
 15. 16.]
[ 1  2  3  4  5  6  7  8  9 10 10 11 12 12 12 13 14 14 15 16]


## Leniar Algebra Operations

In [26]:
a= np.array([[1, 2], [4, 5]])
b= np.array([[7, 8], [10, 11]])

print(np.dot(a, b))
#print(np.matmul(a, b))
print(np.linalg.det(a))
print(np.linalg.inv(a))
print(np.linalg.matrix_rank(a))

[[27 30]
 [78 87]]
-2.9999999999999996
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
2


## np.randon.seed

The np.random.seed() function is crucial for ensuring reproducibility in your code when generating random numbers. Without setting a seed, NumPy will produce different random numbers every time you run the code.

In [ ]:
np.random.seed(1)          # Ensures reproducibility
print(np.random.rand(3, 3)) # Uniform distribution
print(np.random.randn(3, 3))# Normal distribution
print(np.random.randint(1, 10, (3, 3))) # Random integers

[[0.49810907 0.07379201 0.78695147]
 [0.06406733 0.35531036 0.94183695]
 [0.37980329 0.76292007 0.771595  ]]
[[-0.75767414  1.01389243 -0.73843118]
 [ 0.25770667 -1.13745173  1.57814135]
 [-0.17511057 -1.72908882 -0.24407447]]
[[9 6 8]
 [1 4 2]
 [5 5 7]]
