# Heading!!
## Markdown Subheading
### Markdown Paragraph

In [1]:
print("Hello World")
print("Nameste Duniya")

Hello World
Nameste Duniya





# Sum of two Numbers

In [2]:
x=9
y=8
print(x+y)

17


# List Operations

In [3]:
mylist= [1,2,3,4,5]
print(mylist)
mylist.append(6)
print(mylist)
mylist.remove(3)
print(mylist)
mylist.insert(2,3)
print(mylist)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 4, 5, 6]
[1, 2, 3, 4, 5, 6]


# Tuple Operations

In [4]:
mytuple= (1,2,3,4,5)
print(mytuple)
print(mytuple[2])
mytuple= mytuple + (6,)
print(mytuple)
print(mytuple.count(3))
print(mytuple.index(3))

(1, 2, 3, 4, 5)
3
(1, 2, 3, 4, 5, 6)
1
2


# Dictionaries Operations

In [5]:
mydict= {'a':1, 'b':2, 'c':3}
print(mydict)
mydict.update({'d': 4})
print(mydict)

{'a': 1, 'b': 2, 'c': 3}
{'a': 1, 'b': 2, 'c': 3, 'd': 4}


# Numpy

In [6]:
import numpy as np


In [7]:
list1= np.array([1, 2, 3]) 
tuple1= np.array(("1", "2", "3"))
print(list1)
print(tuple1)
print(list1.ndim)
print(tuple1.ndim)

[1 2 3]
['1' '2' '3']
1
1


In [8]:
print(type(list1))
print(list1.dtype)

<class 'numpy.ndarray'>
int32


In [9]:
list2= np.array(["1", "2", "5"], dtype= "i")
print(list1[2])

3


In [10]:
list2= list1.copy()
list2[0]= 5
print(list1)
print(list2)

[1 2 3]
[5 2 3]


In [11]:
list3= list2.view()
list3[0]= 7
print(list3)
print(list2)

[7 2 3]
[7 2 3]


In [12]:
list4= np.array((1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12))
newarray= list4.reshape(4,3)
print(newarray)
#newarray= list4.reshape(-1)
#print(newarray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
newarray[:, [2,0]]= newarray[:, [0,2]]
print(newarray)

[[ 3  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [12 11 10]]


In [14]:
sortarray= np.array([3, 2, 0, 1, 8, 6, 4, 5, 7])
print(np.sort(sortarray))

[0 1 2 3 4 5 6 7 8]


In [15]:
sortarr= np.array(['Lakshy', 'Aman', 'Nandini', 'Diya', 'Rahul', 'Aman'])
print(np.sort(sortarr))

['Aman' 'Aman' 'Diya' 'Lakshy' 'Nandini' 'Rahul']


In [16]:
sortarr= np.array(['Lakshy', 'Aman', 'Shyam', 'Diya'])
x= [True, False, True, False]
newarr= sortarr[x]
print(newarr)
#print("Reverse Order:" ,sortarr[::-1])
print(np.flip(sortarr, axis=0))

['Lakshy' 'Shyam']
['Diya' 'Shyam' 'Aman' 'Lakshy']


In [17]:
arr4= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
condition= arr4>5
newarr= arr4[condition]
print(newarr)

[ 6  7  8  9 10]


In [18]:
print(arr4[2]+ arr4[5])
print(arr4[2]- arr4[5])
print(arr4[2]* arr4[5])
print(arr4[2]/ arr4[5])
print(arr4[2]% arr4[5])

9
-3
18
0.5
3


In [19]:
arr5= np.array([1, 2, 3, 4, 5])
arr6= np.array([6, 7, 8, 9, 10])
print(np.add(arr5, arr6))  #Addition 
print(np.concatenate((arr5, arr6))) #Concatenation


[ 7  9 11 13 15]
[ 1  2  3  4  5  6  7  8  9 10]


There is a difference between add and concate. Remember add function actually performs addition addition while concate function combines the values of an array.

In [20]:
from numpy import random
random.shuffle(arr5)
print(arr5)
random.permutation(arr5)
print(arr5)
print(arr5)

[1 4 2 3 5]
[1 4 2 3 5]
[1 4 2 3 5]


In [21]:
arr7= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 11, 12, 12, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])
print(np.split(arr7, 5))
print(arr7.shape)
print(np.flip(arr7))
print(np.unique(arr7))

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]), array([10, 11, 12, 12, 12]), array([13, 14, 15, 16, 17]), array([18, 19, 20, 21, 22])]
(25,)
[22 21 20 19 18 17 16 15 14 13 12 12 12 11 10 10  9  8  7  6  5  4  3  2
  1]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [22]:
np.savetxt('newfile4.csv', arr7)
arr8= np.loadtxt('newfile4.csv')
print(arr8)
# print(np.load('newfile.npy'))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 10. 11. 12. 12. 12. 13. 14. 15.
 16. 17. 18. 19. 20. 21. 22.]


## Leniar Algebra Operations

In [23]:
from numpy import linalg
# import numpy as np
a= np.array([[1, 2], [4, 5]])
b= np.array([[7, 8], [10, 11]])

# print(np.dot(a, b))
# print(np.matmul(a, b))
print(np.linalg.det(a))
print(np.linalg.inv(a))
print(np.linalg.matrix_rank(a))

-2.9999999999999996
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
2


## np.randon.seed

The np.random.seed() function is crucial for ensuring reproducibility in your code when generating random numbers. Without setting a seed, NumPy will produce different random numbers every time you run the code.

In [24]:
np.random.seed(1)          # Ensures reproducibility
#print(np.random.rand(3, 3)) # Uniform distribution
print(np.random.randn(3, 3))# Normal distribution
print(np.random.randint(1, 10, (3, 3))) # Random integers
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], 4)) # Random choice

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]]
[[3 5 8]
 [8 2 8]
 [1 7 8]]
['e' 'e' 'a' 'u']


In [25]:
print(np.random.choice([1, 2, 3, 4, 5], size= (3, 3))) # Random choice
print(np.random.permutation([1, 2, 3, 4, 5])) # Random permutation

[[2 1 1]
 [4 3 2]
 [1 4 2]]
[5 3 1 4 2]


In [26]:
# Save an array to a CSV file
np.savetxt('array_data.csv', arr7, delimiter=',')

# Load the array back from the CSV file
loaded_array = np.loadtxt('array_data.csv', delimiter=',')
print("Loaded Array:")
print(loaded_array)

np.save('array_data.npy', arr7) # Save an array to a binary file
loaded_array = np.load('array_data.npy') # Load the array back from the binary file
print("Loaded Array:")
print(loaded_array)

Loaded Array:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 10. 11. 12. 12. 12. 13. 14. 15.
 16. 17. 18. 19. 20. 21. 22.]
Loaded Array:
[ 1  2  3  4  5  6  7  8  9 10 10 11 12 12 12 13 14 15 16 17 18 19 20 21
 22]


In [27]:
arr56= np.array([1, 2, 3, 4, 5, 6])
print(np.mean(56))
print(np.median(arr56))
print(np.sum(arr56))

56.0
3.5
21


# Pandas

In pandas data is stored in the format of Dictionary and hence key value pairs are required. On the other hand data shown in the output is in the form of table for better understability and apperance. 

In [28]:
import pandas as pd

In [29]:
dict= { 'Name': ['Rahul' , 'Ram', 'shyam'], 
       'Age': ['26', '14', '17'],
       'City': ['Indore', 'Pune', 'Mumbai']
}

a= pd.DataFrame(dict)
print(a)

    Name Age    City
0  Rahul  26  Indore
1    Ram  14    Pune
2  shyam  17  Mumbai


In [30]:
data= [10, 20, 30, 40, 50]
series= pd.Series(data, index=[1, 2, 3, 4, 5])
print(series)

1    10
2    20
3    30
4    40
5    50
dtype: int64


In [31]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago'], 
    'Gender': ['M', 'M', 'F']
}

df = pd.DataFrame(data, index=['a', 'b', 'c'])
print(df)

      Name  Age         City Gender
a    Alice   25     New York      M
b      Bob   30  Los Angeles      M
c  Charlie   35      Chicago      F


# Operations on DataFrame

In [32]:
print(df.head()) # Display the first 5 rows of the DataFrame

      Name  Age         City Gender
a    Alice   25     New York      M
b      Bob   30  Los Angeles      M
c  Charlie   35      Chicago      F


In [33]:
print(df.tail()) # Display the last 5 rows of the DataFrame 

      Name  Age         City Gender
a    Alice   25     New York      M
b      Bob   30  Los Angeles      M
c  Charlie   35      Chicago      F


In [34]:
print(df.info()) # Display information about the DataFrame

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, a to c
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
 3   Gender  3 non-null      object
dtypes: int64(1), object(3)
memory usage: 120.0+ bytes
None


In [35]:
print(df.describe()) # Display summary statistics of the DataFrame

        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0


In [36]:
print(df.loc['a']) # Access row by label

Name         Alice
Age             25
City      New York
Gender           M
Name: a, dtype: object


In [37]:
print(df['Age']>30) # Boolean indexing

a    False
b    False
c     True
Name: Age, dtype: bool


In [38]:
print(df[df['Age']>30]) # Filter rows based on condition

      Name  Age     City Gender
c  Charlie   35  Chicago      F


In [39]:
print(df.iloc[0]) # Access row by index position
# print(df.iloc[1]) # Access row by index position

Name         Alice
Age             25
City      New York
Gender           M
Name: a, dtype: object


In [40]:
print(df.iloc[0:2]) # Access multiple rows by index position    

    Name  Age         City Gender
a  Alice   25     New York      M
b    Bob   30  Los Angeles      M


In [41]:
print(df.iloc[:, 1]) # Access a specific column by index position
print(df.iloc[:, 1:3]) # Access multiple columns by index position

a    25
b    30
c    35
Name: Age, dtype: int64
   Age         City
a   25     New York
b   30  Los Angeles
c   35      Chicago


# Reading Json file
Here we are going to read a json file Top 100 Largest Banks.json and then will perform data manipulation in this json file. 

In [42]:
data= pd.read_json('Top 100 Largest Banks.json') # Read a CSV file into a DataFrame
print(data)

    Rank                                Bank Name  \
0      1  Industrial and Commercial Bank of China   
1      2               Agricultural Bank of China   
2      3                  China Construction Bank   
3      4                            Bank of China   
4      5                           JPMorgan Chase   
..   ...                                      ...   
95    96                         Raiffeisen Group   
96    97                            Handelsbanken   
97    98                 Industrial Bank of Korea   
98    99                                      DNB   
99   100                      Qatar National Bank   

   Total Assets (2023, US$ billion)  
0                          6,303.44  
1                          5,623.12  
2                          5,400.28  
3                          4,578.28  
4                          3,875.39  
..                              ...  
95                           352.87  
96                           351.79  
97                   

Writing CSV file

In [43]:
data.to_csv('output.csv', index=False) # Write the DataFrame to a CSV file
data.to_excel('output.xlsx', index=False) # Write the DataFrame to an Excel file

Checking Null values in The above CSV file

In [44]:
data.isnull().sum() # Check for missing values in the DataFrame
data.dropna() # Drop rows with missing values
data.fillna(0) # Fill missing values with 0

Rank                                Bank Name  \
0      1  Industrial and Commercial Bank of China   
1      2               Agricultural Bank of China   
2      3                  China Construction Bank   
3      4                            Bank of China   
4      5                           JPMorgan Chase   
..   ...                                      ...   
95    96                         Raiffeisen Group   
96    97                            Handelsbanken   
97    98                 Industrial Bank of Korea   
98    99                                      DNB   
99   100                      Qatar National Bank   

   Total Assets (2023, US$ billion)  
0                          6,303.44  
1                          5,623.12  
2                          5,400.28  
3                          4,578.28  
4                          3,875.39  
..                              ...  
95                           352.87  
96                           351.79  
97                           345.81  
98                           339.21  
99                           338.14  

[100 rows x 3 columns]

Single and Multiple Conditions

In [45]:
data[data["Rank"]< 10] # Filter rows based on condition

Rank                                Bank Name  \
0     1  Industrial and Commercial Bank of China   
1     2               Agricultural Bank of China   
2     3                  China Construction Bank   
3     4                            Bank of China   
4     5                           JPMorgan Chase   
5     6                          Bank of America   
6     7                                     HSBC   
7     8                              BNP Paribas   
8     9           Mitsubishi UFJ Financial Group   

  Total Assets (2023, US$ billion)  
0                         6,303.44  
1                         5,623.12  
2                         5,400.28  
3                         4,578.28  
4                         3,875.39  
5                         3,180.15  
6                         2,919.84  
7                         2,867.44  
8                         2,816.77

Renaming the file

In [46]:
data= pd.read_csv('output.csv') # Read a CSV file into a DataFrame
print(data.head()) # Display the first 5 rows of the DataFrame

   Rank                                Bank Name  \
0     1  Industrial and Commercial Bank of China   
1     2               Agricultural Bank of China   
2     3                  China Construction Bank   
3     4                            Bank of China   
4     5                           JPMorgan Chase   

  Total Assets (2023, US$ billion)  
0                         6,303.44  
1                         5,623.12  
2                         5,400.28  
3                         4,578.28  
4                         3,875.39  


Renaming the column

In [47]:
data.rename(columns={'Total Assets (2023, US$ billion)': 'Assets'}, inplace=True)

In [48]:
data.to_csv('output.csv', index=False) # Write the DataFrame to a CSV file

In [49]:
print(data.duplicated())

0     False
1     False
2     False
3     False
4     False
      ...  
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool


In [50]:
data.drop_duplicates()

Rank                                Bank Name    Assets
0      1  Industrial and Commercial Bank of China  6,303.44
1      2               Agricultural Bank of China  5,623.12
2      3                  China Construction Bank  5,400.28
3      4                            Bank of China  4,578.28
4      5                           JPMorgan Chase  3,875.39
..   ...                                      ...       ...
95    96                         Raiffeisen Group    352.87
96    97                            Handelsbanken    351.79
97    98                 Industrial Bank of Korea    345.81
98    99                                      DNB    339.21
99   100                      Qatar National Bank    338.14

[100 rows x 3 columns]

In [51]:
data.describe() # Display summary statistics of the DataFrame

Rank
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

# Calculating nth percentile of a column

In [55]:
data.Rank.quantile(0.45) # Calculate the nth percentile of the 'Rank' column

45.550000000000004