# HELLO WORLD!!
## Markdown Subheading
### Markdown Paragraph

In [23]:
print("Hello World")
print("Nameste Duniya")

Hello World
Nameste Duniya





# Sum of two Numbers

In [24]:
x=9
y=8
print(x+y)

17


# List Operations

In [25]:
mylist= [1,2,3,4,5]
print(mylist)
mylist.append(6)
print(mylist)
mylist.remove(3)
print(mylist)
mylist.insert(2,3)
print(mylist)


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 4, 5, 6]
[1, 2, 3, 4, 5, 6]


# Tuple Operations

In [26]:
mytuple= (1,2,3,4,5)
print(mytuple)
print(mytuple[2])
mytuple= mytuple + (6,)
print(mytuple)
print(mytuple.count(3))
print(mytuple.index(3))

(1, 2, 3, 4, 5)
3
(1, 2, 3, 4, 5, 6)
1
2


# Dictionaries Operations

In [27]:
mydict= {'a':1, 'b':2, 'c':3}
print(mydict)
mydict.update({'d': 4})
print(mydict)

{'a': 1, 'b': 2, 'c': 3}
{'a': 1, 'b': 2, 'c': 3, 'd': 4}


# Numpy

In [28]:
import numpy as np
import pandas as pd
import matplotlib as plty;

In [29]:
list1= np.array([1, 2, 3]) 
tuple1= np.array(("1", "2", "3"))
print(list1)
print(tuple1)
print(list1.ndim)
print(tuple1.ndim)

[1 2 3]
['1' '2' '3']
1
1


In [30]:
print(type(list1))
print(list1.dtype)

<class 'numpy.ndarray'>
int32


In [31]:
list2= np.array(["1", "2", "5"], dtype= "i")
print(list1[2])

3


In [32]:
list2= list1.copy()
list2[0]= 5
print(list1)
print(list2)

[1 2 3]
[5 2 3]


In [33]:
list3= list2.view()
list3[0]= 7
print(list3)
print(list2)

[7 2 3]
[7 2 3]


In [34]:
list4= np.array((1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12))
newarray= list4.reshape(4,3)
print(newarray)
#newarray= list4.reshape(-1)
#print(newarray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [35]:
newarray[:, [2,0]]= newarray[:, [0,2]]
print(newarray)

[[ 3  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [12 11 10]]


In [36]:
sortarray= np.array([3, 2, 0, 1, 8, 6, 4, 5, 7])
print(np.sort(sortarray))

[0 1 2 3 4 5 6 7 8]


In [37]:
sortarr= np.array(['Lakshy', 'Aman', 'Nandini', 'Diya', 'Rahul', 'Aman'])
print(np.sort(sortarr))

['Aman' 'Aman' 'Diya' 'Lakshy' 'Nandini' 'Rahul']


In [38]:
sortarr= np.array(['Lakshy', 'Aman', 'Nandini', 'Diya'])
x= [True, False, True, False]
newarr= sortarr[x]
print(newarr)
print("Reverse Order:" ,sortarr[::-1])

['Lakshy' 'Nandini']
Reverse Order: ['Diya' 'Nandini' 'Aman' 'Lakshy']


In [39]:
arr4= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
condition= arr4>5
newarr= arr4[condition]
print(newarr)

[ 6  7  8  9 10]


In [40]:
print(arr4[2]+ arr4[5])
print(arr4[2]- arr4[5])
print(arr4[2]* arr4[5])
print(arr4[2]/ arr4[5])
print(arr4[2]% arr4[5])

9
-3
18
0.5
3


In [41]:
arr5= np.array([1, 2, 3, 4, 5])
arr6= np.array([6, 7, 8, 9, 10])
print(np.add(arr5, arr6))  #Addition 
print(np.concatenate((arr5, arr6))) #Concatenation


[ 7  9 11 13 15]
[ 1  2  3  4  5  6  7  8  9 10]


There is a difference between add and concate. Remember add function actually performs addition addition while concate function combines the values of an array.

In [42]:
from numpy import random
random.shuffle(arr5)
print(arr5)
random.permutation(arr5)
print(arr5)
print(arr5)

[1 5 4 3 2]
[1 5 4 3 2]
[1 5 4 3 2]


In [44]:
arr7= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.split(arr7, 5))
print(arr7.shape)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]
(10,)
