# HELLO WORLD!!
## Markdown Subheading
### Markdown Paragraph

In [1]:
print("Hello World")
print("Nameste Duniya")

Hello World
Nameste Duniya





# Sum of two Numbers

In [2]:
x=9
y=8
print(x+y)

17


# List Operations

In [3]:
mylist= [1,2,3,4,5]
print(mylist)
mylist.append(6)
print(mylist)
mylist.remove(3)
print(mylist)
mylist.insert(2,3)
print(mylist)


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 4, 5, 6]
[1, 2, 3, 4, 5, 6]


# Tuple Operations

In [4]:
mytuple= (1,2,3,4,5)
print(mytuple)
print(mytuple[2])
mytuple= mytuple + (6,)
print(mytuple)
print(mytuple.count(3))
print(mytuple.index(3))

(1, 2, 3, 4, 5)
3
(1, 2, 3, 4, 5, 6)
1
2


# Dictionaries Operations

In [5]:
mydict= {'a':1, 'b':2, 'c':3}
print(mydict)
mydict.update({'d': 4})
print(mydict)

{'a': 1, 'b': 2, 'c': 3}
{'a': 1, 'b': 2, 'c': 3, 'd': 4}


# Numpy

In [6]:
import numpy as np
import pandas as pd
import matplotlib as plty;

In [7]:
list1= np.array([1, 2, 3]) 
tuple1= np.array(("1", "2", "3"))
print(list1)
print(tuple1)
print(list1.ndim)
print(tuple1.ndim)

[1 2 3]
['1' '2' '3']
1
1


In [8]:
print(type(list1))
print(list1.dtype)

<class 'numpy.ndarray'>
int32


In [9]:
list2= np.array(["1", "2", "5"], dtype= "i")
print(list1[2])

3


In [10]:
list2= list1.copy()
list2[0]= 5
print(list1)
print(list2)

[1 2 3]
[5 2 3]


In [11]:
list3= list2.view()
list3[0]= 7
print(list3)
print(list2)

[7 2 3]
[7 2 3]


In [12]:
list4= np.array((1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12))
newarray= list4.reshape(4,3)
print(newarray)
#newarray= list4.reshape(-1)
#print(newarray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
newarray[:, [2,0]]= newarray[:, [0,2]]
print(newarray)

[[ 3  2  1]
 [ 6  5  4]
 [ 9  8  7]
 [12 11 10]]


In [14]:
sortarray= np.array([3, 2, 0, 1, 8, 6, 4, 5, 7])
print(np.sort(sortarray))

[0 1 2 3 4 5 6 7 8]


In [15]:
sortarr= np.array(['Lakshy', 'Aman', 'Nandini', 'Diya', 'Rahul', 'Aman'])
print(np.sort(sortarr))

['Aman' 'Aman' 'Diya' 'Lakshy' 'Nandini' 'Rahul']


In [16]:
sortarr= np.array(['Lakshy', 'Aman', 'Nandini', 'Diya'])
x= [True, False, True, False]
newarr= sortarr[x]
print(newarr)
print("Reverse Order:" ,sortarr[::-1])

['Lakshy' 'Nandini']
Reverse Order: ['Diya' 'Nandini' 'Aman' 'Lakshy']


In [17]:
arr4= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
condition= arr4>5
newarr= arr4[condition]
print(newarr)

[ 6  7  8  9 10]


In [18]:
print(arr4[2]+ arr4[5])
print(arr4[2]- arr4[5])
print(arr4[2]* arr4[5])
print(arr4[2]/ arr4[5])
print(arr4[2]% arr4[5])

9
-3
18
0.5
3


In [19]:
arr5= np.array([1, 2, 3, 4, 5])
arr6= np.array([6, 7, 8, 9, 10])
print(np.add(arr5, arr6))  #Addition 
print(np.concatenate((arr5, arr6))) #Concatenation


[ 7  9 11 13 15]
[ 1  2  3  4  5  6  7  8  9 10]


There is a difference between add and concate. Remember add function actually performs addition addition while concate function combines the values of an array.

In [20]:
from numpy import random
random.shuffle(arr5)
print(arr5)
random.permutation(arr5)
print(arr5)
print(arr5)

[3 1 5 4 2]
[3 1 5 4 2]
[3 1 5 4 2]


In [21]:
arr7= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 11, 12, 12, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])
print(np.split(arr7, 5))
print(arr7.shape)
print(np.flip(arr7))
print(np.unique(arr7))

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]), array([10, 11, 12, 12, 12]), array([13, 14, 15, 16, 17]), array([18, 19, 20, 21, 22])]
(25,)
[22 21 20 19 18 17 16 15 14 13 12 12 12 11 10 10  9  8  7  6  5  4  3  2
  1]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [22]:
np.savetxt('newfile.csv', arr7)
arr8= np.loadtxt('newfile.csv')
print(arr8)
print(np.load('newfile.npy'))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 10. 11. 12. 12. 12. 13. 14. 15.
 16. 17. 18. 19. 20. 21. 22.]
[ 1  2  3  4  5  6  7  8  9 10 10 11 12 12 12 13 14 14 15 16]


## Leniar Algebra Operations

In [23]:
from numpy import linalg
# import numpy as np
a= np.array([[1, 2], [4, 5]])
b= np.array([[7, 8], [10, 11]])

print(np.dot(a, b))
print(np.matmul(a, b))
print(np.linalg.det(a))
print(np.linalg.inv(a))
print(np.linalg.matrix_rank(a))

[[27 30]
 [78 87]]
[[27 30]
 [78 87]]
-2.9999999999999996
[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
2


## np.randon.seed

The np.random.seed() function is crucial for ensuring reproducibility in your code when generating random numbers. Without setting a seed, NumPy will produce different random numbers every time you run the code.

In [24]:
np.random.seed(1)          # Ensures reproducibility
#print(np.random.rand(3, 3)) # Uniform distribution
print(np.random.randn(3, 3))# Normal distribution
print(np.random.randint(1, 10, (3, 3))) # Random integers
#print(np.random.choice(['a', 'e', 'i', 'o', 'u'], 4)) # Random choice

[[ 1.62434536 -0.61175641 -0.52817175]
 [-1.07296862  0.86540763 -2.3015387 ]
 [ 1.74481176 -0.7612069   0.3190391 ]]
[[3 5 8]
 [8 2 8]
 [1 7 8]]


In [25]:
print(np.random.choice([1, 2, 3, 4, 5], size= (3, 3))) # Random choice
print(np.random.permutation([1, 2, 3, 4, 5])) # Random permutation

[[2 2 1]
 [5 2 1]
 [1 4 3]]
[4 5 3 1 2]


In [26]:
# Save an array to a CSV file
np.savetxt('array_data.csv', arr7, delimiter=',')

# Load the array back from the CSV file
loaded_array = np.loadtxt('array_data.csv', delimiter=',')
print("Loaded Array:")
print(loaded_array)

np.save('array_data.npy', arr7) # Save an array to a binary file
loaded_array = np.load('array_data.npy') # Load the array back from the binary file
print("Loaded Array:")
print(loaded_array)

Loaded Array:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 10. 11. 12. 12. 12. 13. 14. 15.
 16. 17. 18. 19. 20. 21. 22.]
Loaded Array:
[ 1  2  3  4  5  6  7  8  9 10 10 11 12 12 12 13 14 15 16 17 18 19 20 21
 22]


In [27]:
arr56= np.array([1, 2, 3, 4, 5, 6])
print(np.mean(56))
print(np.median(arr56))
print(np.sum(arr56))

56.0
3.5
21


In [28]:
import pandas as pd

In pandas data is stored in the format of Dictionary and hence key value pairs are required. On the other hand data shown in the output is in the form of table for better understability and apperance. 

In [29]:
dict= { 'Name': ['Rahul' , 'Ram', 'shyam'], 
       'Age': ['26', '14', '17']
}

a= pd.DataFrame(dict)
print(a)

    Name Age
0  Rahul  26
1    Ram  14
2  shyam  17
