# TensorFlow (Solution Manual)

**Only for Samatrix Team - Not to be shared with students**

### Practice 1 - Solution

Try creating:

* 1.1.  A 4D zeros tensor (e.g., for batches of images)
* 1.2.  A 1D tensor with values from 10 to 20


In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
# Solution 1.1
batch_images = tf.zeros([10, 256, 256, 3])  # Batch of 10 RGB images
print("4D Tensor shape:", batch_images.shape)

# Solution 1.2
range_tensor = tf.constant(list(range(10, 21)))
print("1D Range tensor:", range_tensor)

4D Tensor shape: (10, 256, 256, 3)
1D Range tensor: tf.Tensor([10 11 12 13 14 15 16 17 18 19 20], shape=(11,), dtype=int32)


### Practice 2 - Solution

2.1 Create a boolean tensor and check its dtype

2.2 Find the rank of `tf.ones([5, 3, 2])`

In [ ]:
# Solution 2.1
bool_tensor = tf.constant([True, False, True])
print("Boolean tensor dtype:", bool_tensor.dtype)

# Solution 2.2
rank_3_tensor = tf.ones([5, 3, 2])
print("Tensor rank:", rank_3_tensor.ndim)  # 3

Boolean tensor dtype: <dtype: 'bool'>
Tensor rank: 3


### Practice 3 - Solution

3.1 Convert a random NumPy array to tensor, then back to NumPy

3.2 Check if modifications in NumPy affect the original tensor

In [ ]:
# 3.1 Numpy to Tensor
np_array = np.array([[1, 2], [3, 4]])
tensor = tf.constant(np_array)

# 3B. Tensor to Numpy
back_to_np = tensor.numpy()

#### Key Insight:

Changes to NumPy array WON'T affect original tensor (they're separate copies)

### Practice 4 - Solution

4.1 Create a batch of 10 grayscale images (4D tensor)

4.2 Normalize the batch

In [ ]:
# 4.1. Create unnormalized batch (values 0-255)
batch_gray = tf.random.uniform(
    shape=[10, 256, 256, 1], # 1 channel = grayscale
    minval=0,
    maxval=256,  # Exclusive upper bound
    dtype=tf.float32  # Must be float for division
)

# 4.2. Normalize to [0, 1]
batch_gray_normalized = batch_gray / 255.0

# Verification
print("Min value:", tf.reduce_min(batch_gray_normalized).numpy())  # Should be >= 0.0
print("Max value:", tf.reduce_max(batch_gray_normalized).numpy())  # Should be < 1.0

Min value: 2.2738589e-06
Max value: 1.0039208


### Practice 5

Debugging Challenge - Will it work

```
# Broken code - fix it!
try:
    tensor = tf.constant([1, 2, 3], dtype=tf.float16)
    summed = tensor + 50  # Will this work?
except Exception as e:
    print("Error:", e)    # Hint: Check dtypes!
```

Solutions:

Use `tf.cast()` to match dtypes

Try adding `tf.constant(50, dtype=tf.float16)`

In [ ]:
try:
    tensor = tf.constant([1, 2, 3], dtype=tf.float16)
    summed = tensor + tf.constant(50, dtype=tf.float16)  # Match dtypes!
    print("Sum successful:", summed)
except Exception as e:
    print("Error:", e)

Sum successful: tf.Tensor([51. 52. 53.], shape=(3,), dtype=float16)


### Assessment 1 Solutions

In [ ]:
# Identity matrix
identity = tf.eye(5)  # 5x5 identity
print(identity)

# Black RGB image
black_img = tf.zeros([300, 200, 3], dtype=tf.uint8) # 3 for RGB Image

# dtype comparison
print(tf.ones([2, 2]).dtype == tf.zeros([3]).dtype)  # True (both float32)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)
True


### Assessment 2 Solutions

 Create a 2x2 tensor with random values, check if each value is greater than 0.5, and count how many are.

In [ ]:
x = tf.random.uniform([2, 2])
print("Random tensor:\n", x)

greater = x > 0.5
print("Values greater than 0.5:\n", greater)

count = tf.reduce_sum(tf.cast(greater, tf.int32))
print("Number of values > 0.5:", count.numpy())

Random tensor:
 tf.Tensor(
[[0.02883494 0.09124804]
 [0.5897682  0.98973036]], shape=(2, 2), dtype=float32)
Values greater than 0.5:
 tf.Tensor(
[[False False]
 [ True  True]], shape=(2, 2), dtype=bool)
Number of values > 0.5: 2


# Tensor Operations & Broadcasting

### Exercise 2: Reshaping & Broadcasting
#### Objective
Manipulate tensor shapes and observe broadcasting.

```
# Given tensor
D = tf.constant([[1], [2], [3]])  # Shape (3, 1)
E = tf.constant([4, 5, 6])        # Shape (3,)

# Tasks:
# 1. Reshape D to (1, 3)
# 2. Add D and E (broadcasting)
# 3. Reshape E to (3, 1) and multiply with D
```

In [ ]:
import tensorflow as tf

# Given tensors
D = tf.constant([[1], [2], [3]])  # Shape (3, 1)
E = tf.constant([4, 5, 6])        # Shape (3,)

#Task 1: Reshape D to (1, 3)

D_reshaped = tf.reshape(D, [1, 3])  # or D_reshaped = tf.transpose(D)
print("Reshaped D:\n", D_reshaped.numpy())

#Task 2: Add D and E (broadcasting)
result_add = D + E  # Broadcasting happens automatically
print("D + E (broadcasted):\n", result_add.numpy())

#Task 3: Reshape E to (3, 1) and Multiply with D

E_reshaped = tf.reshape(E, [3, 1])  # Column vector
result_mul = D * E_reshaped  # Element-wise multiplication
print("D * E_reshaped:\n", result_mul.numpy())

Reshaped D:
 [[1 2 3]]
D + E (broadcasted):
 [[5 6 7]
 [6 7 8]
 [7 8 9]]
D * E_reshaped:
 [[ 4]
 [10]
 [18]]


: 

### Exercise 3: Tensor Manipulation Functions
#### Objective:
Write reusable functions for tensor operations.

```
# Test cases:
F = tf.constant([[0, 10], [20, 30]])  # Shape (2, 2)
G = tf.constant([5])                   # Shape (1,)
```

* Task 1: Write a function to normalize a tensor (min-max scaling)
* Task 2: Write a function to apply broadcasting addition

In [ ]:
# Task 1: Write a function to normalize a tensor (min-max scaling)
def normalize(tensor):
    min_val = tf.reduce_min(tensor)
    max_val = tf.reduce_max(tensor)
    return (tensor - min_val) / (max_val - min_val)

# Task 2: Write a function to apply broadcasting addition
def add_with_broadcasting(a, b):
    return a + b  # Let TensorFlow handle broadcasting

# Test cases:
F = tf.constant([[0, 10], [20, 30]])  # Shape (2, 2)
G = tf.constant([5])                   # Shape (1,)
print(normalize(F))
print(add_with_broadcasting(F, G))

tf.Tensor(
[[0.         0.33333333]
 [0.66666667 1.        ]], shape=(2, 2), dtype=float64)
tf.Tensor(
[[ 5 15]
 [25 35]], shape=(2, 2), dtype=int32)


### Exercise 4: Debugging Challenge
#### Objective: Fix shape-related errors.

```
# Broken code (fix the shapes!)
H = tf.constant([[1, 2]])  # Shape (1, 2)
I = tf.constant([[3], [4]]) # Shape (2, 1)

# Task: Make this work
J = H + I
```

In [ ]:
H = tf.constant([[1, 2]])  # Shape (1, 2)
I = tf.constant([[3], [4]]) # Shape (2, 1)

J = H + tf.transpose(I)  # Or reshape I to (1, 2)
print(J)

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)


### Exercise 5: Real-World Application

#### Objective: Simulate image preprocessing

```
# Simulate a batch of 3 grayscale images (28x28 pixels)
images = tf.random.uniform([3, 28, 28], maxval=255, dtype=tf.float32)

```
#### Tasks:
1. Normalize pixels to [0, 1]
2. Add a batch of 3 different bias values ([0.1, 0.2, 0.3]) to each image

In [ ]:
# Simulate a batch of 3 grayscale images (28x28 pixels)
images = tf.random.uniform([3, 28, 28], maxval=255, dtype=tf.float32)

normalized_images = images / 255.0
biases = tf.constant([0.1, 0.2, 0.3], shape=[3, 1, 1])  # Shape for broadcasting
biased_images = normalized_images + biases

# Tensor Slicing, Indexing, and Reshaping


### Exercise 1: Slicing & Updating Tensors

#### Objective:
Manipulate image-like tensors (e.g., (height, width, channels)).

**Task 1.1: Extract Patches from an Image**

* Simulate a 5x5 RGB image (shape: [5, 5, 3])
* Extract top-left 2x2 patch

In [ ]:
import tensorflow as tf

# Simulate a 5x5 RGB image (shape: [5, 5, 3])
image = tf.random.uniform([5, 5, 3], maxval=255, dtype=tf.int32)

# Extract top-left 2x2 patch
patch = image[0:2, 0:2, :]  # Shape: [2, 2, 3]
print("Patch shape:", patch.shape)

Patch shape: (2, 2, 3)


### Exercise 2: Dimensionality Manipulation

#### Objective: Reshape and transpose image batches.

**Task 2.1: Flatten an Image Batch**

* Create a Batch of 4 grayscale images (shape: [4, 28, 28])
* Flatten to [4, 784]


In [ ]:
# Batch of 4 grayscale images (shape: [4, 28, 28])
batch = tf.random.uniform([4, 28, 28])

# Flatten to [4, 784]
flattened = tf.reshape(batch, [4, 28*28])
print("Flattened shape:", flattened.shape)

Flattened shape: (4, 784)


**Task 2.2: Swap Color Channels (RGB → BGR)**

* Simulate an RGB image (shape: [224, 224, 3])
* Swap channels using tf.reverse


In [ ]:
# Simulate an RGB image (shape: [224, 224, 3])
rgb_image = tf.random.uniform([224, 224, 3])

# Swap channels using tf.reverse
bgr_image = tf.reverse(rgb_image, axis=[-1])  # Flips the last axis (channels)

print(bgr_image.shape)

(224, 224, 3)


### Exercise 3 (Solved)

### Exercise 4: Debugging Challenge

#### Objective: Fix shape mismatches.

**Task 4.1: Fix Broadcasting Error**

```
# Broken code (shapes: [3, 32, 32, 1] + [3])
batch_images = tf.random.uniform([3, 32, 32, 1])  # Grayscale batch
biases = tf.constant([0.1, 0.2, 0.3])  # Shape [3]
```

In [ ]:
import tensorflow as tf

# Input tensors
batch_images = tf.random.uniform([3, 32, 32, 1])  # Shape [3, 32, 32, 1] (batch of 3 grayscale images)
biases = tf.constant([0.1, 0.2, 0.3])           # Shape [3]

# Solution 1: Reshape biases for broadcasting
fixed_biases = biases[:, tf.newaxis, tf.newaxis, tf.newaxis]  # Shape [3, 1, 1, 1]
corrected = batch_images + fixed_biases

# Solution 2: Alternative using reshape
fixed_biases_alt = tf.reshape(biases, [3, 1, 1, 1])  # Same effect
corrected_alt = batch_images + fixed_biases_alt

# Verification
print("Original shapes:")
print("batch_images:", batch_images.shape)
print("biases:", biases.shape)
print("\nAfter fixing:")
print("fixed_biases shape:", fixed_biases.shape)
print("corrected result shape:", corrected.shape)

Original shapes:
batch_images: (3, 32, 32, 1)
biases: (3,)

After fixing:
fixed_biases shape: (3, 1, 1, 1)
corrected result shape: (3, 32, 32, 1)
